name: Comment Comic Image on New Issue
on:
  issues:
    types:
      - opened

jobs:
  comment_comic_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Comic Image URL
        id: get_comic_image
        run: |
          comic_url=$(curl -s -X POST -H "Content-Type: application/json" -d '{"url":"https://explosm.net/comics/kris-watch","javascript":true}' https://api.scrape.dev/)
          echo "::set-output name=comic_url::$comic_url"

      - name: Comment Comic Image
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `![Cyanide & Happiness Comic Image](${{ steps.get_comic_image.outputs.comic_url }})`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
