name: Comment Comic Image on New Issue
on:
  issues:
    types:
      - opened

jobs:
  comment_comic_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Playwright
        run: npm install playwright

      - name: Extract Comic Image URL
        id: extract_comic_image
        run: |
          const { chromium } = require('playwright');

          async function getComicImage() {
            const browser = await chromium.launch();
            const context = await browser.newContext();
            const page = await context.newPage();
            await page.goto('https://explosm.net/comics/kris-watch');
            const comicImage = await page.getAttribute('#main-comic', 'src');
            await browser.close();
            return comicImage;
          }

          getComicImage().then((comicImage) => {
            console.log(`::set-output name=comic_url::${comicImage}`);
          });

      - name: Comment Comic Image
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `![Cyanide & Happiness Comic Image](${{ steps.extract_comic_image.outputs.comic_url }})`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });


