name: Comment Comic Image on New Issue
on:
  issues:
    types:
      - opened

jobs:
  comment_comic_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pup tool
        run: sudo apt-get install -y pup

      - name: Extract Comic Image URL
        id: extract_comic_image
        run: |
          comic_url=$(curl -s https://explosm.net/comics/kris-watch | pup 'img[id="main-comic"] attr{src}')
          echo "::set-output name=comic_url::$comic_url"

      - name: Comment Comic Image
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `![Cyanide & Happiness Comic Image](${{ steps.extract_comic_image.outputs.comic_url }})`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
