name: Comment XKCD Comic on New Issue
on:
  issues:
    types:
      - opened

jobs:
  comment_xkcd_comic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get XKCD Comic
        id: xkcd
        run: |
          curl -s https://xkcd.com/info.0.json > comic.json
          echo "::set-output name=number::$(jq -r '.num' comic.json)"
          echo "::set-output name=image_url::$(jq -r '.img' comic.json)"
      
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello there! Here's an XKCD comic for you:

            ![XKCD Comic](https://xkcd.com/${{ steps.xkcd.outputs.number }}/)

            ![Comic Image](${{ steps.xkcd.outputs.image_url }})
