name: Create a comment on new issues

on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github ontent"
        run: echo '${{ toJSON(gihub.event }}' | jq
        shell: bash

