name: Create a comment on new issues

on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github ontent"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
        
      #Getting username to print in message
      - name: Get User
        id: usern
        run: echo "set-output name=user_name::${{ github.event.issue.user.login }}"
        
        
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey there ${{ steps.usern.outputs.user_name }}! 
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  
          
